FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN set -e; \
    apt-get update; \
    apt-get install -y netcat-traditional gettext httpie; \
    rm -rf /var/lib/apt/lists/*; \
    pip install --upgrade pip flask

RUN mkdir /code
WORKDIR /code
COPY ./server.py .

ENTRYPOINT ["python","./server.py"]